### ISSUE TITLE
Contributor PRs can't pass

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.ghlint#286]
### Version

Repository

### Reproduction steps

1. Contributor raises a valid PR
2. Wait for CI to complete

### Expected behavior

CI is fully green.

### Actual behavior

![Screenshot_20240529-221626](https://github.com/TWiStErRob/net.twisterrob.ghlint/assets/2906988/d4b975e5-386c-440f-a562-21cea045b165)

### Additional Context

Example: https://github.com/TWiStErRob/net.twisterrob.ghlint/pull/282

**Comment by TWiStErRob** [comment]
@timsearle would you mind opening a dummy PR with a random change to read me, so I can experiment with this?

**Comment by timsearle** [comment]
@TWiStErRob https://github.com/TWiStErRob/net.twisterrob.ghlint/pull/287

**Comment by TWiStErRob** [comment]
Cause: `EnricoMi/publish-unit-test-result-action@v2`

> 2024-05-29 21:41:12 +0000 - publish -  INFO - This action is running on a pull_request event for a fork repository. Pull request comments and check runs cannot be created, so disabling these features. To fully run the action on fork repository pull requests, see https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.16.1/README.md#support-fork-repositories-and-dependabot-branches

**Comment by TWiStErRob** [comment]
Whops, I actually broke `main`, because of this missing check:

https://github.com/TWiStErRob/net.twisterrob.ghlint/pull/290

**Comment by TWiStErRob** [comment]
The `workflow_run` trigger added in #289 has to be on `main`, AND it also only runs from `main`, so the "upload" code has to be on the test branch, and the download code has to be on `main`. At this point I think I need to develop this separately and do a final run on the Test PR.

**Comment by TWiStErRob** [comment]
Started experiments in https://github.com/TWiStErRob/ghlint-contrib-dev
